# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://fereria.github.io/blog"
DefaultContentLanguage  = "ja"
title                   = "Reincarnation+"
theme                   = "hugo-future-imperfect-slim"
paginate                = 10
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true
  hardWraps = true

[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook"]
  hideEmptyStats        = false

  [params.meta]
    description         = ""
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Reincarnation+"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "Reincarnation+"
    paragraph             = "旅行・カメラ・ロードバイク 趣味いろいろ日記"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/icon.jpeg"
      shape               = "circle"
      width               = ""
      alt                 = "Hugo Future Imperfect Slim"

  [params.sidebar]
    about               = ""
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2


  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "categories"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
    
  [[menu.main]]
    name              = "TechPage"
    identifier        = "techpage"
    url               = "https://fereria.github.io/reincarnation_tech"
    pre               = "<i class='fa fa-graduation-cap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Zenn"
    identifier        = "zenn"
    url               = "https://zenn.dev/remiria"
    pre               = "<i class='fa fa-rocket'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Photo"
    identifier        = "photo"
    url               = "https://500px.com/p/megumiando"
    pre               = "<i class='fa fa-picture-o'></i>"
    weight            = 5
    
[Languages]
  [Languages.ja]
    LanguageCode        = "ja"
    LanguageName        = "日本語"
    weight              = 9

[social]
  # Coding Communities
  github                = "fereria"
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  medium                = ""
  # Professional/Business Oriented Communities
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = "fereria"
  googleplus            = ""
  quora                 = ""
  tumblr                = ""
  twitter               = "fereria"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  # Email
  email                 = "work@flame-daybreak.net"

[permalinks]
  posts = '/:year/:month/:slug'